config/routes.rb
Rails.application.routes.draw do 
  resources :livres
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/livre.rb
class Livre < ApplicationRecord


  validates :nom, presence: true
  validates :nombre_de_page, presence: true
  validates :auteur, presence: true




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/livres_controller.rb
class LivresController < ApplicationController

 def index
 	@livres = Livre.all
 end

 def show
 	@livre = Livre.find(params[:id])
 end

 def new
 	@livre = Livre.new
 	
 end

 def edit
 	 @livre = Livre.find(params[:id])

 	
 end

 def create
 	@livre = Livre.new(livres_params)

 	if @livre.save
 	    redirect_to livres_path
 	else
 	   render :new    
 end

end

def update
	 @livre = Livre.find(params[:id])
	 if @livre.update(livres_params)
	 	redirect_to livres_path
	 else
	   render :edit
	 end 	

end

def destroy
     @livre = Livre.find(params[:id])
     @livre.destroy
     redirect_to livres_path
end

 private

def livres_params
	params.require(:livre).permit(:nom, :nombre_de_page, :auteur)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BibliothQue</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <!doctype html>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  
  </head>

  <body>

    
</nav>
<div class="container" style="padding-top: 5rem;">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/livres/edit.html.erb
<h2>Modifier le livre</h2>




<%= form_with model: @livre, local:true do |form| %>
	<p>
		<%= form.label :nom %>
		<%= form.text_field :nom %> 
	</p>

	<p>
		<%= form.label :Nbr_page %>
		<%= form.text_field :nombre_de_page %> 
	</p>

	<p>
		<%= form.label :Auteur %>
		<%= form.text_field :auteur%> 
	</p>

	<p>
		<%= form.submit "Modifier un livre" %>
	</p>

<p>
	<a href="<%= livres_path%>" class="btn btn-primary">Retour</a>
</p>

	<%end%>

app/views/livres/index.html.erb
<h1>Mes livres</h1>
<div id="livres">
	<table class="table table-striped">
		<tr>
		<td>Nom</td>
		<td>Nb_pages</td>
		<td>Auteur</td>
	</tr>

<% @livres.each do |livre| %>
<tr>
<td><%= livre.nom%></td>
<td><%= livre.nombre_de_page%></td>
<td><%= livre.auteur%></td>
<td><%= link_to "voir le livre", livre_path(livre) %></td>
<td><%= link_to "Modifier le livre", edit_livre_path(livre) %></td>
<td><%= link_to "Supprimer le livre", livre_path(livre), method: :delete %></td>
</tr>

	<% end %>
</table>
<br>

<td><%= link_to "Ajouter un nouveau livre", new_livre_path() %></td>

	</div>

app/views/livres/new.html.erb
<h2>Ajouter un nouveau livre</h2>


<%= form_with model: @livre, local:true do |form| %>

     <% if @livre.errors.any? %>
       <h3>une erreur est survenue</h3>
       <%end%>
	<p>
		<%= form.label :nom %>
		<%= form.text_field :nom %> 
	</p>

	<p>
		<%= form.label :Nbr_page %>
		<%= form.text_field :nombre_de_page %> 
	</p>

	<p>
		<%= form.label :Auteur %>
		<%= form.text_field :auteur%> 
	</p>

	<p>
		<%= form.submit "Ajouter un livre" %>
	</p>

<p>
	<a href="<%= livres_path%>" class="btn btn-primary">Retour</a>
</p>

	<%end%>

app/views/livres/show.html.erb
<h3>Nom:<%= @livre.nom %></h3>
<h3>NB_pages: <%= @livre.nombre_de_page %></h3>

<h3>Auteur :<%= @livre.auteur %></h3>


<p>
	<a href="<%= livres_path%>" class="btn btn-primary">Retour</a>
</p>

<p>
  <%= button_to "Supprimer ce livre", @employess, method: :delete %>
  </p>